# Generated by Django 5.2.4 on 2025-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created_at']},
        ),
    ]
