# Generated by Django 5.2.4 on 2025-09-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase'),
        ),
    ]
