# Generated by Django 5.2.4 on 2025-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_purchase_item_alter_purchase_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='Refund',
        ),
    ]
