# Generated by Django 5.2.4 on 2025-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_purchase_item_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
